### ISSUE TITLE
Latest release (module: "src/inert") broke our builds

### ISSUE THREAD

**Issue by timbomckay** [WICG/inert#136]
#135 Broke our builds because it changed which file our webpack pulled in. This probably should've been a breaking change as it took us 2 days to track down why our builds were breaking. 

You should put this in the documentation so people using this in webpack know what to do.

**Comment by bcutler-work** [comment]
This also appears to have broken our bundles on IE11 because the source was no longer being passed through Babel.

**Comment by robdodson** [comment]
ugh... I didn't realize webpack had this ["feature"](https://github.com/webpack/webpack/issues/5756). I didn't think it was a breaking behavior because my assumption was that most folks were using the version that `main` pointed at. We added the `module` version after a different team requested a version that wasn't transpiled to UMD.

In my opinion, it feels a bit weird to ship a version that uses module syntax but transpiles everything else to ES5...

As a short term fix, y'all could pin the dependency to the previous version or try [the `mainFields` webpack option mentioned here](https://github.com/webpack/webpack/issues/5756#issuecomment-405468106). But I realize `mainFields` is annoying because it affects more than just this one dependency. Let me follow up with some peers to see how they're shipping non-transpiled and transpiled code in the same packages to see if I can come up with a solution.

**Comment by robdodson** [comment]
cc @aomarks

**Comment by robdodson** [comment]
Just released a patch version which updates the module field to point at a transpiled version. I'll do a follow up major release tomorrow.

**Comment by aomarks** [comment]
Ping on the major release that's not transpiled?

**Comment by robdodson** [comment]
Just released 3.0

**Comment by aomarks** [comment]
Thank you Rob!
