### ISSUE TITLE
“So every modal dialog must be outside the inert container?”

### ISSUE THREAD

**Issue by simevidas** [WICG/inert#165]
This question was asked [on Twitter](https://twitter.com/equinusocio/status/1357319465285914625). Sorry, I’m not familiar with the proposal, so I thought I’d re-post the question here. I hope that’s not a problem.

**Comment by robdodson** [comment]
For sure, thanks for posting it @simevidas 

Yes, a modal dialog has to be outside of the inert container. We did discuss the idea of letting items inside of the inert container "punch through" but we were concerned that would be chaotic. For example, imagine you load an ad (or some other third party iframe) into a page, and it uninerts itself (or something inside of itself). This could either break your modal dialog experience, or potentially worse, lead to an unexpected security issue (because you have have something inside of an iframe that's active when you don't expect it to be).
