### ISSUE TITLE
Why not have sub tree not-inert id specified?

### ISSUE THREAD

**Issue by Jab2870** [WICG/inert#50]
Why can we not set inert=false on an element under an inert element.  Here is a simple example when this could be useful:

## Full Screen Menu
If I had the follwing html
```html
<body>
<main>
My Main content
There are focusable elements in here
<aside>
My sidebar
There are also focusable elements in here
</aside>
<nav>
This is a full screen menu with focusable links
</nav>
</body>
```

When the Full Screen Menu is activated, I would like everything except the menu to become inert.  I know that in this simple example, setting inert on the main and the asside isn't that diffictult but it would be much easier to set inert=true on the body element then inert=false on the nav element.

**Comment by robdodson** [comment]
When we were first getting into `inert` we debated this specific topic for a long time. We came to the conclusion that it's better for `inert` to be consistent, otherwise you could never really trust it. For example, say you put `inert` on your `<body>` but elsewhere in the page you load an `<iframe>` for an ad and tucked in that ad is an `inert=false`. Developers don't often have fine grained control over the ads code that gets loaded into their site, so this scenario is very possible and would make `inert` kind of useless.

We proposed a separate primitive for the use case you're describing, tentatively called `blockingElements`. You can check out [a polyfill here](https://github.com/PolymerLabs/blockingElements). Basically `blockingElements` lets you say "everyone except for me is inert", whereas `inert` lets you say "I am inert". Here's a write up I did to explain both in a bit more detail https://robdodson.me/building-better-accessibility-primitives/. Hope that helps!

**Comment by robdodson** [comment]
Gonna close this but happy to reopen for discussion if folks would like to keep the conversation going

**Comment by Jab2870** [comment]
@robdodson , thanks for your responce.  Sorry for my late reply.  WOuld you consider doing an A11ycast on blockingElements?

**Comment by robdodson** [comment]
yep I've added it to my list of things I need to talk about :)
